[WIP] Added --version option
gen-classroom/projet-besseau_cerottini_maziero_ogi pull request #37
Opened 2021-03-15 18:05 UTC by MazieroMarco

Need to check projects structure before merge.
Possibility to add a class for the options ?

Closes #29

2021-03-19 09:54 UTC, LeonardBesseau commented
I saw that coloring was possible with [picocli](https://picocli.info/#_version_info_with_colors) so please add this behaviour before i can accept your PR

2021-03-19 09:55 UTC, LeonardBesseau requested changes
See my comment about coloring.

2021-03-22 10:39 UTC, LeonardBesseau commented
![image](https://user-images.githubusercontent.com/52856615/111977652-47298c00-8b03-11eb-8aef-d10650747d82.png)
If you want to visualise the colors in intelij

2021-03-22 10:42 UTC, LeonardBesseau commented on src/test/java/ch/heig_vd/app/MainTest.java
> +        int result2 = new CommandLine(new Main()).execute("statique", "--version");
It seems it just checks if the program exit normally not that the program displayed anything.
Maybe add a check to verify the program outputted something. (Don't need to check that the version is correct but that is at least outputted version -XXXXXX

2021-03-22 10:42 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Main.java
>          System.exit(new CommandLine(new Main()).execute(args));
Do we need to create two command line object ?
Or can we reuse the previous one ?

2021-03-23 22:05 UTC, MazieroMarco commented on src/main/java/ch/heig_vd/app/Main.java
>          System.exit(new CommandLine(new Main()).execute(args));
Updated, no additional object is created when executing options and commands.

2021-03-23 22:05 UTC, MazieroMarco commented on src/test/java/ch/heig_vd/app/MainTest.java
> +        int result2 = new CommandLine(new Main()).execute("statique", "--version");
Tests updates, it now checks if the ouput contains the keyword "Statique"

2021-03-24 21:03 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Main.java
>          System.exit(new CommandLine(new Main()).execute(args));
Nice. Good job

2021-03-24 21:03 UTC, LeonardBesseau commented on src/test/java/ch/heig_vd/app/MainTest.java
> +        int result2 = new CommandLine(new Main()).execute("statique", "--version");
Ok. Well done

2021-03-24 21:04 UTC, LeonardBesseau approved these changes
All good. All demands are met

2021-03-24 21:04 UTC, merged