[WIP] Adding Init command
gen-classroom/projet-besseau_cerottini_maziero_ogi pull request #39
Opened 2021-03-19 11:41 UTC by NicolasOgi

Need to finish tests

2021-03-19 11:43 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Main.java
> +@Command(name = "statique", subcommands = {Build.class, New.class, Serve.class, Clean.class, Init.class},
Good to add class for command

2021-03-19 11:49 UTC, LeonardBesseau requested changes

2021-03-19 11:49 UTC, LeonardBesseau commented on pom.xml
> +      <groupId>com.googlecode.json-simple</groupId>
Need an explanation of why we need this library and what are the alternative.

2021-03-19 11:49 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Init.java
> +@CommandLine.Command(name = "Init")
Comments ? to explain what the class is for ?

2021-03-19 11:49 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Init.java
> +        jsonObject.put("description", "Une ambiance délétère");
Good description.

2021-03-19 11:49 UTC, LeonardBesseau commented on src/test/java/ch/heig_vd/app/InitTest.java
> +
Need test

2021-03-19 11:49 UTC, LeonardBesseau commented on src/test/java/ch/heig_vd/app/InitTest.java
> +
Need test

2021-03-19 11:49 UTC, LeonardBesseau commented on src/test/java/ch/heig_vd/app/InitTest.java
> +        File dir = new File("./mon/site/");
test need to test that the path manages absolute and relative path. If you want just wait for commit for the clean command #32 for an example.

2021-03-19 11:49 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Init.java
> +        File dir = new File("./mon/site/");
Path should not be hardcoded but given as a parameter

2021-03-19 11:49 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Init.java
> +
Need parameter for path. See #32 when it will be updated for example

2021-03-21 13:33 UTC, NicolasOgi commented on pom.xml
> +      <groupId>com.googlecode.json-simple</groupId>
It is a lightweight library provided by Google to create Json object. The alternative is this one : https://mvnrepository.com/artifact/org.json/json/20201115 (full and official ?). I think the lightweight version is better for what we have to do.

2021-03-21 13:35 UTC, NicolasOgi commented on src/main/java/ch/heig_vd/app/Init.java
> +@CommandLine.Command(name = "Init")
I have followed this tutorial to create JSONObject : https://www.tutorialspoint.com/how-to-write-create-a-json-file-using-java. They used json-simple library so that is why I chose to use it too.

2021-03-22 10:04 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Init.java
> +@CommandLine.Command(name = "Init")
Ok. seems good to me

2021-03-24 21:27 UTC, LeonardBesseau commented on pom.xml
> +      <groupId>com.googlecode.json-simple</groupId>
Ok. That will suffice

2021-03-26 12:40 UTC, LeonardBesseau commented on src/main/java/ch/heig_vd/app/Init.java
> +        // Permet de normaliser le chemin pour retirer les éventuels "//" ou ".." insérés par erreur
Please change the language

2021-03-26 12:41 UTC, LeonardBesseau requested changes
Just change the comment

2021-03-26 12:48 UTC, NicolasOgi commented
NEED REVIEW NOW

2021-03-26 12:52 UTC, LeonardBesseau approved these changes
All good

2021-03-26 12:53 UTC, merged