Manuel utilisateur
gen-classroom/projet-besseau_cerottini_maziero_ogi pull request #96
Opened 2021-05-28 10:38 UTC by Insuline13

will close #84

2021-05-28 22:38 UTC, Insuline13 commented
Je dois attendre le merge de la commande serve corrigée pour terminer

2021-05-28 23:29 UTC, Insuline13 commented
Soit on remplace directement le readme par le manuel utilisateur, soit on mentionne le manuel utilisateur dans le readme. Il est très équivalent au readme. La différence est qu'il est en français et qu'il y a un exemple en plus.

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +`build` et `template` sont des dossiers spéciaux. Tous les fichiers en format Markdown incluts seront ignorés. Le dossier `build ` est utilisé comme sortie pour la conversion des fichiers Markdown et
"inclus" ou "inclut" ?

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +`build` et `template` sont des dossiers spéciaux. Tous les fichiers en format Markdown incluts seront ignorés. Le dossier `build ` est utilisé comme sortie pour la conversion des fichiers Markdown et
y a plusieurs modèle pour le site

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +
Rajouter que si des métadonnées sont attendues par le template mais pas présente la conversion échoue

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +
{{md content}} ça affiche le contenue mais avec la transformation de contenu markdown en html. Est-ce qu'on précise que on peut inserr du contenu brut aussi ?

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Fichier correcte:
Fichier correct. Pas de féminin

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Fichier incorrecte:
Fichier incorrect. Pas de féminin

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Fichier correcte:
Fichier correct. Pas de féminin

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Nous allons premièrement commencer par afficher la version du générateur de site statique avec la commande `java -jar <release>.jar -v`.
"premièrement commencer" est un pléonasme

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +
Peut-être expliquer les différences entre les templates et ce qu'on essaye de montrer

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +
Est-il possible d'ajouter un exemple avec le file watcher ?

2021-06-01 09:35 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Pour compiler le site statique, utilisez la commande `java -jar <release>.jar build <dossier>`. Cette commande va créer un dossier `build` dans le dosser `<dossier>` contenant un fichier `index.html`
Techniquement l'index.md n'est pas obligatoire pour le build (et pour le serve mais à vérifier) donc il est géré comme un fichier normal

2021-06-02 19:41 UTC, LeonardBesseau requested changes

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +La conversion échoue si des métadonnées sont attendues par le template mais qu'elles ne sont pas présentent.
présentes

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +
All good

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +
Ok

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Ce template comporte la particularité d'insérer un autre fichier avec `{{> menu}}`. Il insérera à cet emplacement le fichier `menu.html`.
Un peu bizzare la tournure. "Le fichier `menu.html`sera inséré à cet emplacement parait plus naturel"

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Ce template va insérer un fichier `noMeta.md` ne comportant pas de metadatas.
NON. Ce template n'attend aucune métadonnée donc la seule métadonne nécessaire pour utiliser ce template est la métadonnée template. Ou bien on renomme ce template en default.html et par default, les fichiers n'ont besoin d'aucune métadonnées

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Nous allons maintenant ajouter trois templates dans notre dossier `template` (en plus du `default.html`) déjà existant.
Techniquement, le menu.html est pas vraiment un template donc uniquement 2 template et un fichier annexe.

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Nous allons dans un troisième temps compiler notre site statique et activer le fileWatcher avec la commande `java -jar <release>.jar build -w mon/site`.
Pourquoi activer le filewatcher si on serve avec le filewatcher ensuite ?

2021-06-02 19:41 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +
Ok.

2021-06-02 19:50 UTC, LeonardBesseau commented on manuel_utilisateur.md
> +Pour compiler le site statique, utilisez la commande `java -jar <release>.jar build <dossier>`. Cette commande va créer un dossier `build` dans le dosser `<dossier>` contenant un fichier `index.html`
Des trucs à dire ?

2021-06-04 08:22 UTC, LeonardBesseau approved these changes
Looks good to me

2021-06-04 09:36 UTC, MazieroMarco approved these changes
Very good example files ! Well done !

2021-06-04 09:40 UTC, NicolasOgi approved these changes
SGTM 👍🏻

2021-06-04 09:41 UTC, merged